# Generated by Django 2.1.5 on 2019-02-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=250)),
                ('khode_photo', models.ImageField(blank=True, default='default.jpg', upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
