# Generated by Django 2.1.5 on 2019-02-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_media_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='khode_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
