# Generated by Django 2.1.5 on 2019-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20190211_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='khode_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='photo_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='media',
            name='Black_White',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='BottomRight_X',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='BottomRight_Y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='Resize_Height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='Resize_Width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='Rotate_Degree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='Share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='TopLeft_X',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='TopLeft_Y',
            field=models.IntegerField(default=0),
        ),
    ]
