# Generated by Django 2.1.5 on 2019-02-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20190211_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
