# Generated by Django 2.1.5 on 2019-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20190211_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
