# Generated by Django 2.1.5 on 2019-02-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20190211_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='BottomRight_X',
            new_name='Bottom',
        ),
        migrations.RemoveField(
            model_name='media',
            name='BottomRight_Y',
        ),
        migrations.RemoveField(
            model_name='media',
            name='TopLeft_X',
        ),
        migrations.RemoveField(
            model_name='media',
            name='TopLeft_Y',
        ),
        migrations.AddField(
            model_name='media',
            name='Left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='Right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='media',
            name='Top',
            field=models.IntegerField(default=0),
        ),
    ]
